version: '3'

services:
  app:
    build: ./
    command: pm2-dev ./server/index.js
    expose:
      - 8080
    environment:
      NODE_ENV: production
      SERVER_PORT: 8080
      JWT_SECRET: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
      MONGO_HOST: mongodb://mongodb/test
    restart: always
    depends_on:
      - mongodb
  
  nginx:
    image: nginx:1.14
    links:
      - app
    ports:
      - '80:80'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      
  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - '27017:27017'
